baseURL = "https://cv.constantin-krueger.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "Constantin Krüger CV"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
